// src/library/LibraryBook.tsx
import { convertFileSrc } from "@tauri-apps/api/tauri";
import { createMemo, Show } from "solid-js";
import { BookDatabaseEntry } from "src/backend/library";
import { openFolder } from "src/backend/system";

// use:__ directives
import { contextMenu } from "src/contextMenu";
false && contextMenu;

export default function LibraryBook(props: {
    entry: BookDatabaseEntry;
    onOpen?: (entry: BookDatabaseEntry) => void;
    onDelete?: (entry: BookDatabaseEntry) => void;
}) {
    const coverUrl = createMemo(() =>
        props.entry.coverPath ? convertFileSrc(props.entry.coverPath) : null
    );

    return (
        <button
            class="bg-gray-100"
            onClick={() => props.onOpen?.(props.entry)}
            use:contextMenu={[
                {
                    label: "Open Folder",
                    action: () => openFolder(props.entry.epubPath),
                },
                {
                    label: "Delete",
                    action: () => props.onDelete?.(props.entry),
                },
            ]}
        >
            <Show when={coverUrl()}>
                <img
                    class="h-52 object-contain mx-auto"
                    src={coverUrl()}
                    alt={props.entry.metaTitle}
                    draggable={false}
                />
            </Show>
            <p class="text-sm">{props.entry.metaTitle}</p>
        </button>
    );
}

// src/library/LibraryBook.svelte
<script lang="ts">
    import { convertFileSrc } from "@tauri-apps/api/tauri";
    import { createEventDispatcher } from "svelte";
    import { contextMenu } from "src/contextmenu";
    import { openFolder, type BookDatabaseEntry } from "../backend";

    export let bookEntry: BookDatabaseEntry;

    let coverUrl: string;
    $: coverUrl = bookEntry.coverPath
        ? convertFileSrc(bookEntry.coverPath)
        : null;

    let dispatch = createEventDispatcher<{
        open: BookDatabaseEntry;
        delete: BookDatabaseEntry;
    }>();
</script>

<button
    on:click={() => dispatch("open", bookEntry)}
    use:contextMenu={[
        { label: "Open Folder", action: () => openFolder(bookEntry.epubPath) },
        { label: "Delete", action: () => dispatch("delete", bookEntry) },
    ]}
>
    {#if coverUrl}
        <img src={coverUrl} alt={bookEntry.metaTitle} draggable="false" />
    {/if}
    <p>{bookEntry.metaTitle}</p>
</button>

<style>
    button {
        min-height: 200px;
    }

    img {
        height: 200px;
        object-fit: contain;
    }
</style>
