// src/FileDropHandler.svelte
<script lang="ts">
    import { onDestroy } from "svelte";
    import { listen } from "@tauri-apps/api/event";
    import { createEventDispatcher } from "svelte";
    import { filterByExtension } from "./util/path";

    export let hovering: boolean = false;
    export let allowedExtensions: string[] = null;

    const hoverHandler = listen<string[]>("tauri://file-drop-hover", () => {
        hovering = true;
    });
    const cancelledHandler = listen<string[]>(
        "tauri://file-drop-cancelled",
        () => {
            hovering = false;
        }
    );

    const dispatch = createEventDispatcher<{ fileDrop: string[] }>();
    const fileDropHandler = listen<string[]>(
        "tauri://file-drop",
        async (event) => {
            hovering = false;

            let allowedFiles = allowedExtensions
                ? await filterByExtension(event.payload, allowedExtensions)
                : event.payload;

            if (allowedFiles.length > 0) {
                dispatch("fileDrop", allowedFiles);
            }
        }
    );

    onDestroy(async () => {
        // Unsubscribe from events
        for (const unlisten of await Promise.all([
            hoverHandler,
            fileDropHandler,
            cancelledHandler,
        ])) {
            unlisten();
        }
    });
</script>

// src/FileDropHandler.tsx
import { listen } from "@tauri-apps/api/event";
import { onCleanup } from "solid-js";
import { filterByExtension } from "./util/path";

export function FileDropHandler(props: {
    onHover?: (value: boolean) => void;
    onFileDrop?: (files: string[]) => void;
    allowedExtensions?: string[];
}) {
    const hoverHandler = listen<string[]>("tauri://file-drop-hover", () => {
        props.onHover?.(true);
    });
    const cancelledHandler = listen("tauri://file-drop-cancelled", () => {
        props.onHover?.(false);
    });
    const fileDropHandler = listen<string[]>(
        "tauri://file-drop",
        async (event) => {
            props.onHover?.(false);

            let allowedFiles = props.allowedExtensions
                ? await filterByExtension(
                      event.payload,
                      props.allowedExtensions
                  )
                : event.payload;

            if (allowedFiles.length > 0) {
                props.onFileDrop?.(allowedFiles);
            }
        }
    );

    onCleanup(async () => {
        // Unsubscribe from events
        for (const unlisten of await Promise.all([
            hoverHandler,
            fileDropHandler,
            cancelledHandler,
        ])) {
            unlisten();
        }
    });

    return <></>;
}
